# Generated by Django 4.2.6 on 2023-10-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailingstore', '0002_order_total_amount_currency_alter_order_total_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
