# Generated by Django 4.2.6 on 2023-10-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailingstore', '0002_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='products/'),
        ),
    ]
